#!/bin/sh
NOW=$(date +"%b-%d-%y")
LOGFILE="/home/wfsbea7/dev/scripts/wfs_logs/wfs-$NOW.log"
exec >> $LOGFILE 2>&1
echo
echo
echo "####################################################################"
echo `date`
echo "####################################################################"
echo starting jack;
jackd -R -d alsa -r44100 -dmergedcards -o128&
sleep 4;
echo starting wfscollider;
sclang /home/wfsbea7/dev/scripts/startwfs.scd&
